### ISSUE TITLE
Is it possible for wg-meshconf to offer exit-node? 

### ISSUE THREAD

**Issue by raaron773** [k4yt3x/wg-meshconf#38]
Hi,

I am wondering if I can assign a peer as exit-node? Is this something which wg-meshconf can already do and I missed it or does it not support it yet? Any chance you can add a support for exit node ?

Thanks!

**Comment by k4yt3x** [comment]
What is it that you're trying to achieve here? Let every node access the Internet from the "exit-node"? Sounds like what's required would be:

- For every node that's not the exit node, set `AllowedIPs` of the exit node to be `0.0.0.0/0`.
- Apply masquerading on the firewall of the exit node.

These are not supported by wg-meshconf, since it's not the goal of this project. wg-meshconf can't access the firewall either.

**Comment by raaron773** [comment]
I want to use one of the nodes as a proxy so that it acts like a nordvpn or something similar. This is what I am wondering if it's achievable. Sorry for not being clear enough and thank you.

**Comment by k4yt3x** [comment]
If you don't need every node in the network to access each other, consider spoke & hub where you have one central server acting as the server, then all the spokes (VPN clients) will only need to have one peer which is the server instead of what wg-meshconf does which is every peer will have all other nodes as peers. Spoke & hub will be much simpler if that's what you're after.

However, wg-meshconf is a mesh network configuration generator, so this tool won't be for that.

**Comment by raaron773** [comment]
I see. I understand. I will stick with wg-meshconf and maybe install wg docker on the server to use it as a proxy for now much simpler than spokes and hubs imho. Appreciate it!
